### ISSUE TITLE
impossible to compile

### ISSUE THREAD

**Issue by Linoa235** [Lynnette177/Rigel-Overwatch-Internal#3]
Hi there are 3 errors line 35 impossible to compile: C3872/C3873 (d3d9) 0xa3/0xa9 on this one with auto update and on the recently internally updated dll there is one more

**Comment by cedy88** [comment]
its true, its not possible to compile the project.

**Comment by froggerwill** [comment]
> Hi I'm coming back to tell you that it's good I updated but I had a crash and I had difficulty launching the external several times for the menu to appear

could you help me to run it I am a beginner in that domain and would like to learn from you if possible.
