### ISSUE TITLE
求大佬在论坛发布一个编译成dll的中文版文件

### ISSUE THREAD

**Issue by huajiaohe** [Lynnette177/Rigel-Overwatch-Internal#6]

**Comment by YouPLe9999** [comment]
https://www.unknowncheats.me/forum/overwatch/623396-rigel-compile-files.html

english ver
chinese ver is not released

**Comment by huajiaohe** [comment]
thanks

**Comment by Lynnette177** [comment]
我给你补个蛋！！！
天天找我补补补 我头都大了
我凭！什！么！

**Comment by huajiaohe** [comment]
大佬，我没有要冒犯你的意思，不愿意我不打扰就是了，我还是很敬佩你的，之前在unknowme上看到大佬的帖子和贡献，大佬觉得不方便给就算了，感谢大佬在unknowme上的分享，那个github上的issue我会删除，我在unknowme上下载了一个别人编译好的外部，但是在游戏里面aimbot不起作用，不知道大佬有没有看见那个帖子，谢谢大佬的工作。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lynnette177/Rigel-Overwatch-Internal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月29日(星期四) 上午9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lynnette177/Rigel-Overwatch-Internal] 求大佬在论坛发布一个编译成dll的中文版文件 (Issue #6)





 
我给你补个蛋！！！
 天天找我补补补 我头都大了
 我凭！什！么！

**Comment by Lynnette177** [comment]
没事 你应该只是看不懂这个梗

**Comment by Lynnette177** [comment]
> 大佬，我没有要冒犯你的意思，不愿意我不打扰就是了，我还是很敬佩你的，之前在unknowme上看到大佬的帖子和贡献，大佬觉得不方便给就算了，感谢大佬在unknowme上的分享，那个github上的issue我会删除，我在unknowme上下载了一个别人编译好的外部，但是在游戏里面aimbot不起作用，不知道大佬有没有看见那个帖子，谢谢大佬的工作。
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "Lynnette177/Rigel-Overwatch-Internal"                                                                                    ***@***.***&gt;;
> 
> 发送时间:&nbsp;2024年2月29日(星期四) 上午9:53
> 
> ***@***.***&gt;;
> 
> ***@***.******@***.***&gt;;
> 
> 主题:&nbsp;Re: [Lynnette177/Rigel-Overwatch-Internal] 求大佬在论坛发布一个编译成dll的中文版文件 (Issue #6)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 我给你补个蛋！！！
> 
>  天天找我补补补 我头都大了
> 
>  我凭！什！么！
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

【我给你补个蛋，蛋我也补不起-哔哩哔哩】 https://b23.tv/nmx6iK4

**Comment by huajiaohe** [comment]
哈哈哈哈，giao哥

**Comment by huajiaohe** [comment]
用visual studio编译sln文件，生成解决方案，在编译模式下编译成dll文件，但是我试过报错，编译不出来，而且这个带联网验证和密钥的，你得删掉这部分代码才能用。

**Comment by Lynnette177** [comment]
放你妈的屁 你以为我以前怎么用的
你不会用 你就别用 别一天天在这找事 跟脑残一样
&nbsp;


Mercy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月11日(星期一) 上午8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lynnette177/Rigel-Overwatch-Internal] 求大佬在论坛发布一个编译成dll的中文版文件 (Issue #6)





 
用visual studio编译sln文件，生成解决方案，在编译模式下编译成dll文件，但是我试过报错，编译不出来，而且这个带联网验证和密钥的，你得删掉这部分代码才能用。
