### ISSUE TITLE
detected my account.. qaq

### ISSUE THREAD

**Issue by YouPLe9999** [Lynnette177/Rigel-Overwatch-Internal#7]
![image](https://github.com/Lynnette177/Rigel-Overwatch-Internal/assets/105734928/33e86532-0651-416b-8660-719f3f18dd0f)

**Comment by YouPLe9999** [comment]
***Information on account closure***

hello.

Account: YOUBOT.MAGUNI@GMAIL.COM
ACCOUNT ACTION: ACCOUNT CLOSED - OVERWATCH ACCOUNT
Reason: Unauthorized cheat program (hereinafter referred to as “hack”)

Recently, activity has been discovered on this account using unauthorized cheat programs, also known as “hacks,” to undermine the intended player experience.

The account holder is responsible for all actions on this account. We suspend and close accounts to protect our players and services in accordance with the Blizzard End User License Agreement (https://blizzard.com/company/legal/eula.html).

We do not take this decision lightly. This closure has been taken after our team has carefully reviewed the relevant evidence. Support will not reverse this closure and may not respond to appeals. Detailed information can be found in a separate document (https://battle.net/support/article/2639).

Thank you for your understanding on this matter.

thank you

Customer Support Team
blizzard entertainment
https://battle.net/

**Comment by Exotikcheatt** [comment]
Simply because you use detect driver man lol..

**Comment by YouPLe9999** [comment]
I used DLL Inject from Process Hacker 2. If there is a problem with this program, can you tell me how to do it?

**Comment by Exotikcheatt** [comment]
process hacker for inject into any game with anti-cheat = results ban

**Comment by YouPLe9999** [comment]
So what should I use??

**Comment by huajiaohe** [comment]
Perhaps you are being too aggressive in your approach. Maybe try to adjust and act more appropriately, as it would be more acceptable.

**Comment by Exotikcheatt** [comment]
> So what should I use??

your own injector its OW2 or OW
