### ISSUE TITLE
seem detected my account

### ISSUE THREAD

**Issue by huajiaohe** [Lynnette177/Rigel-Overwatch-Internal#8]
<img width="591" alt="屏幕截图_20240227_092540" src="https://github.com/Lynnette177/Rigel-Overwatch-Internal/assets/126372630/5fdc1b79-5c0c-4bd8-954c-65a4a3f8bab0">
I use extreme injector and standard injection method, manual map cannot be used in Windows 11. Internal seem no safe.

**Comment by YouPLe9999** [comment]
<b>me too 🥹🥹🥹</b>

**Comment by huajiaohe** [comment]
Using an external version may be safer, but I am not sure how to compile it successfully.

**Comment by Exotikcheatt** [comment]
exterm injector into overwatch.................... lol result ban brother..
